import axios from "axios";

//////VARIABLES PARA LAS ACCIONES////////

export const GET_SELLER_DETAIL = "GET_SELLER_DETAIL";
export const CREATE_SELLER = "CREATE_SELLER";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const DELETE_PRODUCT = "CREATE_PRODUCT";
